Resources Management UX Merge
PThorpe92/UnlockEdv2 pull request #5
Opened 2024-09-15 13:27 UTC by jtucholski

## Description of the change

This PR largely focuses on changes to the Resources Management page. There are a lot of areas where the code can be refactored after which would extend into creation of new components & types. 

## Screenshot(s)

![image](https://github.com/user-attachments/assets/cc47ef33-0578-4004-a3c4-7f5c06e9a776)
![image](https://github.com/user-attachments/assets/bc2fa933-de1e-45fe-94b1-2c1ff0cf422b)

2024-09-17 21:36 UTC, calisio requested changes
I left some comments on this PR, some of which might be addressed in a later ticket (they are marked with a 💡). Some are small changes, some are things to consider, some are just suggestions. Feel free to push back on any of it. Also, comments might be out of order in the main feed-- I was jumping around in the files so it might be a bit of back and forth.

Lastly, I noticed a small bug having to do with drag and drop, which is a larger discussion since we may consider implementing a library later to make it easier. I've attached a video to show the issue.

https://github.com/user-attachments/assets/cc60ac20-1360-429a-add7-111091144d5a

It seems like you can drag links into the left hand side and it creates a div for it there. Not sure what the best fix is for this.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/ResourcesSideBar.tsx
> +        />
instead of passing this info in like this, the idea was that we would call the backend to render all of these that are stored in the backend - i think the right call is a GET to `/api/open-content` but I would double check on that. Hard coding was just a temporary solution for the demo, but now that we've updated this might as well do it completely.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/ExternalLink.tsx
> +            target="_blank"
I think we also have to add `rel="noopener noreferrer"` here, I must have missed it originally

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/ResourcesCategoryCard.tsx
> +    const cardClasses = `card card-compact overflow-hidden`;
Shouldn't we just declare this inline on the div? I don't think we need to declare it as a separate variable up here

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/ResourcesSideBar.tsx
> +        />
Also, rather than passing in each individual component, it might just be easier to pass in the whole open content provider (as in pass in the whole object that is returned, such as Kolibri, which contains the following fields since it is of type `OpenContentProvider`:
```
type OpenContentProvider struct {
	DatabaseFields
	Url                string            `gorm:"size:255;not null;unique" json:"url"`
	ProviderPlatformID uint              `json:"provider_platform_id"`
	Thumbnail          string            `json:"thumbnail_url"`
	CurrentlyEnabled   bool              `json:"currently_enabled"`
	Description        string            `json:"description"`
	ProviderPlatform   *ProviderPlatform `gorm:"foreignKey:ProviderPlatformID;constraint:OnDelete SET NULL" json:"-"`
}
```
and then you would access each of these in the `StaticContentCard.tsx`. See comment on this file for more reference.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/StaticContentCard.tsx
> +}: StaticContentCardProps) {
So by passing in an object of type `OpenContentProvider`, we could eliminate all of these lines of code. It would be reduced down to just `export default function StaticContentCard({provider}: {provider: OpenContentProvider}) { .. rest of code ....}`. Also, I would say that StaticContentCard might not be the best thing to name this component. Because this card will only be used for Open Content providers, I would name it as such. That's just how I would approach it though- not sure if there was some other motive behind the naming of this component.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/StaticContentCard.tsx
> +                src={imgSrc}
so then down here, you would access the info by doing `provider.imgSrc`. Again, this is how I would approach it but feel free to push back!

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/StaticContentCard.tsx
> +                <ExternalLink url={linkUrl}>{linkText}</ExternalLink>
Also, because this text is similar with all the Open Content providers, you wouldn't need to pass in the linkText in here- you could just directly write it as `<ExternalLink url={linkUrl}>Explore {provider.name}'s Content</ExternalLink>` (not sure if provider.name is correct- would need to check in the backend). This way, it will be the exact same format for each of the open content providers and it won't be prone to any small variations

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/forms/AddResourceCollectionForm.tsx
> +                    length={null}
just double checking- is there a backend constraint to the URL length? if there isnt, ignore this but just want to double check so we dont deal with an issue later on

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/forms/AddResourceCollectionForm.tsx
> +                <p className="text-sm text-red-500 mt-2">
can you change this to `text-error`?

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/forms/AddResourceCollectionForm.tsx
> +                <TextInput
I think something we need to consider here is that the user can now put in a value that is not of type URL. Instead of using TextInput here should we just create an input that has a type="url"? Open to discussion on this one; just want to make sure we know the user can type in things that are not a URL and then it wouldn't function as we wanted it to.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                        data-tip="Edit Collection"
Could we make this "Edit Collection Name", just so the user immediately knows what exactly it is. Or it could be "Rename Collection" or something of the sort.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/forms/AddResourceCollectionForm.tsx
> +    const [errorMessage, _] = useState('');
Declaring this errorMessage here seems pretty pointless in my opinion, because it's never changing. Maybe we should change the error message to be optional props so we don't have to pass anything in if we don't have an error message? That way we dont even need to declare this use state nor pass it into the submit button.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Components/forms/EditResourceCollectionForm.tsx
> +    const [errorMessage, _] = useState();
again, similar statement to above. If we never need to set the error message to anything different, I think we should just make errorMessage an optional param in `SubmitButton.tsx`

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
>      const { data, error, mutate, isLoading } = useSWR('/api/left-menu');
add in the type, I believe it should be `useSWR<ServerResponse<ResourceCategory>>('/api/left-menu')` but correct if wrong.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +    const [collectionList, setCollectionList] = useState([]);
specify type (an array of Resources?) aka `useState<EditableResourceCategory[]>([])`

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +import { TrashIcon } from '@heroicons/react/24/outline';
can be on the same import line

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +import { CloudArrowUpIcon } from '@heroicons/react/16/solid';
Bars3Icon should be Bars4Icon, and should be imported with the others above under @heroicons/react/24/outline. Same with CloudArrowUpIcon

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                            </div>
💡 This is addressed in a comment left on [this issue](https://github.com/UnlockedLabs/UnlockEdv2/issues/383). Instead of using this, we should directly use the icon as the button (with whatever action you need as the onclick), so this would look like this:
```
<div className="tooltip" data-tip="Add Collection">
    <PlusCircleIconSolid className="w-6 my-auto text-teal-3" onClick={() => addCollectionModal.current?.showModal()} />
</div>
```

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                    <div className="card flex flex-col px-8 py-4 grow">
💡 this will be addressed in a future ticket so it is just a note for now-- these should be the same spacing that is shown in the figma file. So, for example, the px on the left pane should be px-6. the padding in the overall element (line 191) should be a px-8. this just gives all of the pages the same consistency across components.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                        {' '}
what are these extra lines of code between each that are just spaces? Would we be able to remove them ?

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
>                      </div>
💡 Would we be able to make this button the full width of the above container? It also should be in the container, but if that messes with drag and drop (since I know that is a pain) no worries it can live outside of here if it needs to. It being inside of the container just might make it a bit more intuitive for the user to what changes are being published (aka the changes inside of that container).

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                    <h3 className="card-title text-sm">{collection.name}</h3>
Rather than using `text-sm` try to always use the default text sizes we have. On the figma this one is listed as Body, so you would just have to add the tag `body` inside className.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                    </thead>
💡 using `className="table"` is a default that is built into DaisyUI, and personally I don't love the way it makes it look in here. The table tag can still be used, but just without the className of table and the proportions adjusted accordingly. This would also help the inputs to fill more space getting rid of the awkward spacing between them, which could add more room to display the titles and the link. Not an urgent fix by any means.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                                                ? 'bg-gray-200'
if you could use one of our listed colors this would be great. this will make sure that it adapts the color for dark mode. (ie use `bg-grey-1` or something of the sort)

2024-09-17 21:36 UTC, calisio commented on frontend/tailwind.config.js
> +                    '--pale-yellow': '#FFF3D4',
this is a good catch. I think we also need to fix it under "dark" on here (line 58)

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +    const cardClasses = `card card-compact grow overflow-visible ${collection.isModified ? 'bg-pale-yellow' : ''} ${selected ? 'border border-dark-yellow' : ''}`;
add in `bg-inner-background` for dark mode

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +        <div className="card">
add in `bg-inner-background` for dark mode

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                    <h3 className="card-title text-sm">{collection.name}</h3>
💡 `card-body` and `card-title` are built into daisyUI and don't fit our styling. the styling tags we can use are listed in `app.css`. Its a bit confusing because we use daisyUI in some places, but our own styled components in other places, but I am trying to shift away from using daisyUI and more towards building our own components/styling so we have complete control over everything we create. Daisy is super complicated to alter their base styles, so when in doubt look at the `app.css` file or do it inline (if it is not a universal style that will be used other places). For this, the `<h3>` should already have the necessary styling, so you can remove the whole `className="card-title text-sm"`. the div that has`card-body` can be removed completely, and instead we can just add `py-4 px-6` to the div that has `className="card"` (it might be worth looking into the padding for card components in general and making this a universal padding used. but, we need to make sure it wont impact the other layouts that use `card` and evaluate from there).

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                        <tr className="border-grey-600">
we shouldn't be using colors like this-- try to stick to only colors listed within `tailwind.config.js`. It will ensure that the colors work both in light and dark mode. I'm actually not certain what this color gives to the row.

2024-09-17 21:36 UTC, calisio commented on frontend/src/Pages/ResourcesManagement.tsx
> +                    <h3 className="card-title text-sm">{collection.name}</h3>
actually, I think that the origin of this problem is listed in a comment down below (the one talking about not using `card-body` or `card-title` as they are built into daisyUI)

2024-09-18 20:43 UTC, jtucholski commented on frontend/src/Components/ResourcesSideBar.tsx
> +        />
I agree with you but would ask if we can consider it out of scope for this task. I don't see Content Provider types defined in the frontend or backend seed data for Open Content Providers. Do you?

2024-09-18 20:45 UTC, jtucholski commented on frontend/src/Components/StaticContentCard.tsx
> +}: StaticContentCardProps) {
When writing this I didn't realize that there was some dynamic nature to our content providers. I'd say see my previous comment again and maybe a future task can be to remove static providers and replace it with dynamic calls to the API to get Open Content Providers?

2024-09-19 10:17 UTC, jtucholski commented on frontend/src/Components/forms/AddResourceCollectionForm.tsx
> +                    length={null}
No backend length, the field type is `jsonb`

2024-09-19 14:11 UTC, jtucholski commented
@calisio With respect to the bug you observed I think we need to restrict what types of elements can be dropped onto a drag/drop container. We could look into fixing that here or we might want to make that part of the ticket that goes with replacing the functionality with a drag and drop library. 

What do you think?

2024-09-19 14:53 UTC, calisio commented on frontend/src/Components/ResourcesSideBar.tsx
> +        />
Right, I see what you are saying. But, I will say that I don't think that updating this StaticContent card is in the scope of this task either. I suggested this change because it feels like if we are going to create a new component, we might as well update and fix it completely. I'm okay with creating a different task for this, but in the future maybe a new task should be made to handle the entire issue? I might be missing something regarding why this was updated in this ticket, though, so please let me know if so!

2024-09-19 14:54 UTC, calisio commented on frontend/src/Components/StaticContentCard.tsx
> +}: StaticContentCardProps) {
Ya gotcha, we can do that 👍

2024-09-19 14:55 UTC, calisio commented on frontend/src/Components/forms/AddResourceCollectionForm.tsx
> +    const [errorMessage, _] = useState('');
If you feel like this should be a different ticket though, totally cool with that too

2024-09-19 17:03 UTC, calisio commented
Honestly, ya I think that we should just leave it for now and fix it when we add a drag drop library. If bug isn't breaking the functionality maybe we just leave it for later? 
I did find a different bug when testing to make sure that saving collections worked as expected. I attached a video below.
[Screen Recording 2024-09-19 at 11.58.43 AM.zip](https://github.com/user-attachments/files/17063293/Screen.Recording.2024-09-19.at.11.58.43.AM.zip)

2024-09-20 21:16 UTC, merged